@startuml
entity Enemy
/'
entity Player
entity Player_Bullet
entity Enemy_Bullet
entity Explotion
entity Player_Input
'/


class CSurface {
    Color : Pygame.Vector2
    Size : Pygame.Vector 2
    from_surface(pygame.Surface)
}
class CTransform {
    Pos : Pygame.Vector2
}
class CVelocity {
    Vel : Pygame.Vector2
}
class CAnimation {
    Number_frames: Int
    animation_list : List[AnimationData]
}
class AnimationData {
    name: Str
    start: Int
    end: Int
    frameRate: Float
}

/'
class CPlayerState {
    state : PlayerState
}
class PlayerState {
    Enum
}
class CInputCommnad {
    name : Str
    key: inter
    phase : CommandPhase
}
class CommandPhase {
    Enum
}
'/

class CTagEnemy

/'
class CTagBullet_Player
class CTagBullet_Enemy
class CTagExplotion
class CTagPlayer
'/

stereotype system_animation
stereotype system_movement
stereotype system_rendering
stereotype system_screen_bounce
/'
stereotype system_collision_enemy_bullet
stereotype system_collision_player_enemy
stereotype system_explosion_kill
stereotype system_input_player
stereotype system_player_state
stereotype system_screen_bullet
stereotype system_screen_player
'/

CAnimation <|-- AnimationData
/'
CPlayerState <|-- PlayerState
CInputCommnad <|-- CommandPhase
'/

Enemy *-- CTagEnemy
Enemy *-- CAnimation
Enemy *-- CSurface
Enemy *-- CTransform

@enduml
