@startuml
entity Enemy
entity Player_Bullet
entity Input_Left
entity Input_Right
entity Input_Fire
entity Player
entity Explotion
entity Enemy_Bullet

class CSurface {
    Color : Pygame.Vector2
    Size : Pygame.Vector 2
    from_surface(pygame.Surface)
}
class CTransform {
    Pos : Pygame.Vector2
}
class CVelocity {
    Vel : Pygame.Vector2
}
class CAnimation {
    Number_frames: Int
    animation_list : List[AnimationData]
}
class AnimationData {
    name: Str
    start: Int
    end: Int
    frameRate: Float
}
class CInputCommnad {
    name : Str
    key: inter
    phase : CommandPhase
}
class CommandPhase {
    Enum
}

class CTagEnemy
class CTagBullet
class CTagExplosion
class CTagPlayer
class CTagEnemyBullet
class CTagPlayerBullet

stereotype system_animation
stereotype system_movement
stereotype system_rendering
stereotype system_screen_bullet
stereotype system_input_player
stereotype system_collision_enemy_bullet
stereotype system_enemy_block_movement
stereotype system_explosion_kill
stereotype system_enemy_fire
stereotype system_player_limits

CAnimation <|-- AnimationData
CInputCommnad <|-- CommandPhase

Enemy *-- CTagEnemy
Enemy *-- CAnimation
Enemy *-- CSurface
Enemy *-- CTransform
Enemy *-- CVelocity
system_enemy_block_movement --* Enemy : Modify

Player_Bullet *-- CTagPlayerBullet
Player_Bullet *-- CSurface
Player_Bullet *-- CTransform
Player_Bullet *-- CVelocity
system_screen_bullet --* Player_Bullet : Delete

Input_Fire *-- CInputCommnad
Input_Left *-- CInputCommnad
Input_Right *-- CInputCommnad
system_input_player --* Input_Fire : Invoke
system_input_player --* Input_Left : Invoke
system_input_player --* Input_Right : Invoke

system_collision_enemy_bullet --* Explotion : Create
Explotion *-- CTagExplosion
Explotion *-- CAnimation
Explotion *-- system_explosion_kill :Delete

Player *-- CTagPlayer
Player *-- CSurface
Player *-- CTransform
Player *-- CVelocity
system_player_limits --* Player : Modify

system_enemy_fire --* Enemy_Bullet : Create
Enemy_Bullet *-- CTagEnemyBullet
Enemy_Bullet *-- CTagBullet
Enemy_Bullet *-- CSurface
Enemy_Bullet *-- CTransform
Enemy_Bullet *-- CVelocity
system_screen_bullet --* Enemy_Bullet : Delete

system_animation --* CAnimation
system_animation --* CSurface

system_movement --* CTransform
system_movement --* CVelocity

system_rendering --* CTransform
system_rendering --* CSurface

@enduml
